//! 道路编辑 FlatBuffers 生成物与 generated-only `unsafe` 边界检查。

use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const FLATBUFFERS_VERSION: &str = "25.12.19";
const SCHEMA_PATH: &str = "schemas/road-editing/v1/road-editing.fbs";
const CHECKED_RUST_PATH: &str =
    "crates/laneflow-road-editing-wire/src/generated/road-editing_generated.rs";
const WIRE_MANIFEST_PATH: &str = "crates/laneflow-road-editing-wire/Cargo.toml";
const WIRE_PACKAGE_ROOT: &str = "crates/laneflow-road-editing-wire";
const OUTPUT_ROOT: &str = "target/road-editing-codegen";
const GENERATED_HEADER: &[u8] =
    b"// automatically generated by the FlatBuffers compiler, do not modify\n// @generated\n";

pub(crate) fn run(args: &[String]) -> Result<(), String> {
    let flatc = parse_flatc_path(args)?;
    let repository_root =
        std::env::current_dir().map_err(|error| format!("无法解析仓库根目录: {error}"))?;
    require_repository_root(&repository_root)?;
    check_unsafe_boundary(&repository_root)?;
    check_flatbuffers_runtime_version(&repository_root)?;
    check_flatc_version(&flatc)?;

    let output_root = repository_root.join(OUTPUT_ROOT);
    reset_output_root(&output_root)?;
    let rust_output = output_root.join("rust");
    let cpp_output = output_root.join("cpp");
    let csharp_output = output_root.join("csharp");
    for output in [&rust_output, &cpp_output, &csharp_output] {
        fs::create_dir_all(output).map_err(|error| {
            format!("无法创建 codegen 输出目录 `{}`: {error}", output.display())
        })?;
    }

    run_flatc(&flatc, "--rust", &rust_output, &repository_root)?;
    compare_generated_rust(
        &repository_root.join(CHECKED_RUST_PATH),
        &rust_output.join("road-editing_generated.rs"),
    )?;

    run_flatc(&flatc, "--cpp", &cpp_output, &repository_root)?;
    require_generated_extension(&cpp_output, "h")?;
    run_flatc(&flatc, "--csharp", &csharp_output, &repository_root)?;
    require_generated_extension(&csharp_output, "cs")?;

    println!(
        "道路编辑 codegen 已通过：{}；Rust canonical bytes clean，C++/C# probe 已生成，generated-only unsafe 边界已闭合",
        flatc.display()
    );
    Ok(())
}

fn parse_flatc_path(args: &[String]) -> Result<PathBuf, String> {
    match args {
        [flag, path] if flag == "--flatc" && !path.is_empty() => Ok(PathBuf::from(path)),
        _ => Err(
            "用法：cargo +1.96.0 run --locked -p xtask -- check-road-editing-codegen --flatc <flatc-path>"
                .to_string(),
        ),
    }
}

fn require_repository_root(root: &Path) -> Result<(), String> {
    for path in ["Cargo.toml", SCHEMA_PATH, CHECKED_RUST_PATH] {
        if !root.join(path).is_file() {
            return Err(format!("必须从 LaneFlow 仓库根目录运行；缺少 `{path}`"));
        }
    }
    Ok(())
}

fn check_flatc_version(flatc: &Path) -> Result<(), String> {
    let output = Command::new(flatc)
        .arg("--version")
        .output()
        .map_err(|error| format!("无法执行 `{}`: {error}", flatc.display()))?;
    if !output.status.success() {
        return Err(format!(
            "`{} --version` 失败，exit={}",
            flatc.display(),
            output.status
        ));
    }
    let stdout = String::from_utf8(output.stdout)
        .map_err(|error| format!("flatc version 输出不是 UTF-8: {error}"))?;
    let actual = stdout.trim();
    let expected = format!("flatc version {FLATBUFFERS_VERSION}");
    if actual != expected {
        return Err(format!(
            "flatc 版本不匹配：预期 `{expected}`，实际 `{actual}`"
        ));
    }
    Ok(())
}

fn check_flatbuffers_runtime_version(repository_root: &Path) -> Result<(), String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .current_dir(repository_root)
        .args([
            "metadata",
            "--format-version",
            "1",
            "--no-deps",
            "--locked",
            "--manifest-path",
            WIRE_MANIFEST_PATH,
        ])
        .output()
        .map_err(|error| format!("无法读取 wire crate Cargo metadata: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "`cargo metadata --manifest-path {WIRE_MANIFEST_PATH}` 失败，exit={}，stderr={}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    require_flatbuffers_runtime_pin(&output.stdout)
}

fn require_flatbuffers_runtime_pin(metadata: &[u8]) -> Result<(), String> {
    let metadata: serde_json::Value = serde_json::from_slice(metadata)
        .map_err(|error| format!("Cargo metadata 不是有效 JSON: {error}"))?;
    let packages = metadata
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "Cargo metadata 缺少 packages 数组".to_string())?;
    let wire_package = packages
        .iter()
        .find(|package| {
            package.get("name").and_then(serde_json::Value::as_str)
                == Some("laneflow-road-editing-wire")
        })
        .ok_or_else(|| "Cargo metadata 缺少 laneflow-road-editing-wire package".to_string())?;
    let dependencies = wire_package
        .get("dependencies")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "wire package metadata 缺少 dependencies 数组".to_string())?;
    let expected = format!("={FLATBUFFERS_VERSION}");
    let mut runtime_count = 0;
    for runtime in dependencies.iter().filter(|dependency| {
        dependency.get("name").and_then(serde_json::Value::as_str) == Some("flatbuffers")
    }) {
        runtime_count += 1;
        let actual = runtime
            .get("req")
            .and_then(serde_json::Value::as_str)
            .ok_or_else(|| "flatbuffers runtime metadata 缺少版本约束".to_string())?;
        if actual != expected {
            let target = runtime
                .get("target")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("all targets");
            return Err(format!(
                "flatbuffers runtime 版本不匹配：target `{target}` 预期精确约束 `{expected}`，实际 `{actual}`"
            ));
        }
    }
    if runtime_count == 0 {
        return Err("wire package 缺少 flatbuffers runtime 依赖".to_string());
    }
    Ok(())
}

fn reset_output_root(output_root: &Path) -> Result<(), String> {
    if output_root.exists() {
        fs::remove_dir_all(output_root).map_err(|error| {
            format!(
                "无法清理固定 codegen 输出目录 `{}`: {error}",
                output_root.display()
            )
        })?;
    }
    Ok(())
}

fn run_flatc(
    flatc: &Path,
    language: &str,
    output: &Path,
    repository_root: &Path,
) -> Result<(), String> {
    let status = Command::new(flatc)
        .current_dir(repository_root)
        .arg(language)
        .arg("-o")
        .arg(output)
        .arg(SCHEMA_PATH)
        .status()
        .map_err(|error| format!("无法执行 `{}` {language}: {error}", flatc.display()))?;
    if !status.success() {
        return Err(format!(
            "`{} {language} -o {} {SCHEMA_PATH}` 失败，exit={status}",
            flatc.display(),
            output.display()
        ));
    }
    Ok(())
}

fn compare_generated_rust(checked: &Path, regenerated: &Path) -> Result<(), String> {
    let checked_bytes = fs::read(checked).map_err(|error| {
        format!(
            "无法读取 checked-in Rust 生成物 `{}`: {error}",
            checked.display()
        )
    })?;
    let regenerated_bytes = fs::read(regenerated).map_err(|error| {
        format!(
            "flatc 未生成预期 Rust 文件 `{}`: {error}",
            regenerated.display()
        )
    })?;
    let checked_canonical = canonical_generated_source(&checked_bytes)?;
    let regenerated_canonical = canonical_generated_source(&regenerated_bytes)?;

    if !checked_canonical.starts_with(GENERATED_HEADER) {
        return Err(format!(
            "checked-in Rust 生成物 `{}` 缺少固定 generated header",
            checked.display()
        ));
    }
    if checked_canonical != regenerated_canonical {
        let first_difference = checked_canonical
            .iter()
            .zip(&regenerated_canonical)
            .position(|(left, right)| left != right)
            .unwrap_or(checked_canonical.len().min(regenerated_canonical.len()));
        return Err(format!(
            "Rust 生成物不是 clean regeneration：canonical byte offset {first_difference} 首次不同，checked={} bytes，regenerated={} bytes；请使用固定 flatc 重新生成并提交 `{}`",
            checked_canonical.len(),
            regenerated_canonical.len(),
            checked.display()
        ));
    }
    Ok(())
}

fn canonical_generated_source(bytes: &[u8]) -> Result<Vec<u8>, String> {
    let mut canonical = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        match bytes[index] {
            b'\r' => {
                if bytes.get(index + 1) != Some(&b'\n') {
                    return Err(format!("生成物在 byte offset {index} 含有非 CRLF 的裸 CR"));
                }
                canonical.push(b'\n');
                index += 2;
            }
            byte => {
                canonical.push(byte);
                index += 1;
            }
        }
    }
    Ok(canonical)
}

fn require_generated_extension(root: &Path, extension: &str) -> Result<(), String> {
    let mut files = Vec::new();
    collect_files(root, &mut files)?;
    if files.iter().any(|path| {
        path.extension() == Some(OsStr::new(extension))
            && fs::metadata(path).is_ok_and(|metadata| metadata.len() > 0)
    }) {
        return Ok(());
    }
    Err(format!(
        "flatc probe `{}` 未产生非空 .{extension} 文件",
        root.display()
    ))
}

fn check_unsafe_boundary(repository_root: &Path) -> Result<(), String> {
    let workspace_manifest = fs::read_to_string(repository_root.join("Cargo.toml"))
        .map_err(|error| format!("无法读取 workspace Cargo.toml: {error}"))?;
    if !toml_has_value(
        &workspace_manifest,
        "workspace.lints.rust",
        "unsafe_code",
        "forbid",
    ) {
        return Err(
            "workspace 必须保持 `[workspace.lints.rust] unsafe_code = \"forbid\"`".to_string(),
        );
    }

    let wire_manifest = fs::read_to_string(repository_root.join(WIRE_MANIFEST_PATH))
        .map_err(|error| format!("无法读取 `{WIRE_MANIFEST_PATH}`: {error}"))?;
    if !toml_has_value(&wire_manifest, "lints.rust", "unsafe_code", "allow") {
        return Err(format!(
            "`{WIRE_MANIFEST_PATH}` 必须是唯一 generated-only `unsafe_code = \"allow\"` 边界"
        ));
    }

    let manifests = workspace_manifest_paths(repository_root)?;
    let wire_manifest_path = repository_root
        .join(WIRE_MANIFEST_PATH)
        .canonicalize()
        .map_err(|error| format!("无法解析 `{WIRE_MANIFEST_PATH}`: {error}"))?;
    for manifest in manifests {
        let manifest = manifest
            .canonicalize()
            .map_err(|error| format!("无法解析 `{}`: {error}", manifest.display()))?;
        if manifest == wire_manifest_path {
            continue;
        }
        let text = fs::read_to_string(&manifest)
            .map_err(|error| format!("无法读取 `{}`: {error}", manifest.display()))?;
        if toml_has_value(&text, "lints.rust", "unsafe_code", "allow") {
            return Err(format!(
                "generated 路径外不得放宽 unsafe lint：`{}`",
                manifest.display()
            ));
        }
        if !toml_has_value(&text, "lints", "workspace", "true") {
            return Err(format!(
                "手写 workspace package 必须继承 `unsafe_code = \"forbid\"`：`{}`",
                manifest.display()
            ));
        }
    }

    let generated_path = repository_root.join(CHECKED_RUST_PATH);
    check_wire_rust_sources(&repository_root.join(WIRE_PACKAGE_ROOT), &generated_path)?;
    Ok(())
}

fn workspace_manifest_paths(repository_root: &Path) -> Result<Vec<PathBuf>, String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .current_dir(repository_root)
        .args([
            "metadata",
            "--format-version",
            "1",
            "--no-deps",
            "--locked",
            "--manifest-path",
            "Cargo.toml",
        ])
        .output()
        .map_err(|error| format!("无法读取 workspace Cargo metadata: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "`cargo metadata --manifest-path Cargo.toml` 失败，exit={}，stderr={}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    parse_workspace_manifest_paths(&output.stdout)
}

fn parse_workspace_manifest_paths(metadata: &[u8]) -> Result<Vec<PathBuf>, String> {
    let metadata: serde_json::Value = serde_json::from_slice(metadata)
        .map_err(|error| format!("Cargo metadata 不是有效 JSON: {error}"))?;
    let members = metadata
        .get("workspace_members")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "Cargo metadata 缺少 workspace_members 数组".to_string())?;
    let packages = metadata
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "Cargo metadata 缺少 packages 数组".to_string())?;
    let mut manifests = Vec::with_capacity(members.len());
    for member in members {
        let member = member
            .as_str()
            .ok_or_else(|| "Cargo metadata workspace member 不是字符串".to_string())?;
        let package = packages
            .iter()
            .find(|package| package.get("id").and_then(serde_json::Value::as_str) == Some(member))
            .ok_or_else(|| format!("Cargo metadata 缺少 workspace member package `{member}`"))?;
        let manifest = package
            .get("manifest_path")
            .and_then(serde_json::Value::as_str)
            .ok_or_else(|| format!("workspace package `{member}` 缺少 manifest_path"))?;
        manifests.push(PathBuf::from(manifest));
    }
    manifests.sort_unstable();
    Ok(manifests)
}

fn check_wire_rust_sources(package_root: &Path, generated_path: &Path) -> Result<(), String> {
    let mut wire_sources = Vec::new();
    collect_extension_files(package_root, OsStr::new("rs"), &mut wire_sources)?;
    for source in wire_sources {
        if source == generated_path {
            continue;
        }
        let text = fs::read_to_string(&source)
            .map_err(|error| format!("无法读取 `{}`: {error}", source.display()))?;
        if contains_unsafe_token(&text) || text.contains("allow(unsafe_code)") {
            return Err(format!(
                "wire package 的手写 Rust 路径不得包含 unsafe：`{}`",
                source.display()
            ));
        }
    }
    Ok(())
}

fn toml_has_value(text: &str, section: &str, key: &str, expected: &str) -> bool {
    let mut current_section = "";
    for raw_line in text.lines() {
        let line = raw_line.split('#').next().unwrap_or_default().trim();
        if line.starts_with('[') && line.ends_with(']') {
            current_section = line.trim_matches(&['[', ']'][..]).trim();
            continue;
        }
        if current_section != section {
            continue;
        }
        let Some((actual_key, actual_value)) = line.split_once('=') else {
            continue;
        };
        if actual_key.trim() == key && actual_value.trim().trim_matches('"') == expected {
            return true;
        }
    }
    false
}

fn contains_unsafe_token(text: &str) -> bool {
    text.match_indices("unsafe").any(|(index, token)| {
        let before = text[..index].chars().next_back();
        let after = text[index + token.len()..].chars().next();
        !before.is_some_and(is_identifier_character) && !after.is_some_and(is_identifier_character)
    })
}

fn is_identifier_character(character: char) -> bool {
    character == '_' || character.is_alphanumeric()
}

fn collect_files(root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if !root.is_dir() {
        return Err(format!("目录不存在：`{}`", root.display()));
    }
    for entry in
        fs::read_dir(root).map_err(|error| format!("无法枚举 `{}`: {error}", root.display()))?
    {
        let path = entry
            .map_err(|error| format!("无法读取 `{}` 的目录项: {error}", root.display()))?
            .path();
        if path.is_dir() {
            collect_files(&path, files)?;
        } else if path.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

fn collect_extension_files(
    root: &Path,
    extension: &OsStr,
    files: &mut Vec<PathBuf>,
) -> Result<(), String> {
    let mut candidates = Vec::new();
    collect_files(root, &mut candidates)?;
    files.extend(
        candidates
            .into_iter()
            .filter(|path| path.extension() == Some(extension)),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_exact_flatc_argument() {
        assert_eq!(
            parse_flatc_path(&["--flatc".to_string(), "tools/flatc".to_string()]),
            Ok(PathBuf::from("tools/flatc"))
        );
        assert!(parse_flatc_path(&[]).is_err());
        assert!(parse_flatc_path(&["--flatc".to_string()]).is_err());
        assert!(
            parse_flatc_path(&[
                "--flatc".to_string(),
                "flatc".to_string(),
                "extra".to_string()
            ])
            .is_err()
        );
    }

    #[test]
    fn canonicalizes_only_line_endings() {
        assert_eq!(
            canonical_generated_source(b"a\r\nb\n"),
            Ok(b"a\nb\n".to_vec())
        );
        assert!(canonical_generated_source(b"a\rb").is_err());
    }

    #[test]
    fn reads_exact_toml_lint_values() {
        let manifest = "[lints]\nworkspace = true\n\n[lints.rust]\nunsafe_code = \"allow\"\n";
        assert!(toml_has_value(manifest, "lints", "workspace", "true"));
        assert!(toml_has_value(
            manifest,
            "lints.rust",
            "unsafe_code",
            "allow"
        ));
        assert!(!toml_has_value(
            manifest,
            "workspace.lints.rust",
            "unsafe_code",
            "forbid"
        ));
    }

    #[test]
    fn derives_every_manifest_from_workspace_membership() {
        let metadata = br#"{
            "workspace_members": ["wire 0.0.0", "example 0.0.0"],
            "packages": [
                {"id": "wire 0.0.0", "manifest_path": "E:/repo/crates/wire/Cargo.toml"},
                {"id": "example 0.0.0", "manifest_path": "E:/repo/examples/foo/Cargo.toml"},
                {"id": "outside 0.0.0", "manifest_path": "E:/outside/Cargo.toml"}
            ]
        }"#;

        assert_eq!(
            parse_workspace_manifest_paths(metadata).unwrap(),
            [
                PathBuf::from("E:/repo/crates/wire/Cargo.toml"),
                PathBuf::from("E:/repo/examples/foo/Cargo.toml"),
            ]
        );
    }

    #[test]
    fn requires_runtime_version_to_match_flatc() {
        let matching = br#"{
            "packages": [{
                "name": "laneflow-road-editing-wire",
                "dependencies": [{"name": "flatbuffers", "req": "=25.12.19"}]
            }]
        }"#;
        assert_eq!(require_flatbuffers_runtime_pin(matching), Ok(()));

        let mismatched = br#"{
            "packages": [{
                "name": "laneflow-road-editing-wire",
                "dependencies": [{"name": "flatbuffers", "req": "=25.9.23"}]
            }]
        }"#;
        assert!(require_flatbuffers_runtime_pin(mismatched).is_err());
    }

    #[test]
    fn requires_every_target_runtime_version_to_match_flatc() {
        let matching = br#"{
            "packages": [{
                "name": "laneflow-road-editing-wire",
                "dependencies": [
                    {"name": "flatbuffers", "req": "=25.12.19", "target": "cfg(not(windows))"},
                    {"name": "flatbuffers", "req": "=25.12.19", "target": "cfg(windows)"}
                ]
            }]
        }"#;
        assert_eq!(require_flatbuffers_runtime_pin(matching), Ok(()));

        let mismatched = br#"{
            "packages": [{
                "name": "laneflow-road-editing-wire",
                "dependencies": [
                    {"name": "flatbuffers", "req": "=25.12.19", "target": "cfg(not(windows))"},
                    {"name": "flatbuffers", "req": "=25.9.23", "target": "cfg(windows)"}
                ]
            }]
        }"#;
        let error = require_flatbuffers_runtime_pin(mismatched).unwrap_err();
        assert!(error.contains("cfg(windows)"));
        assert!(error.contains("=25.9.23"));
    }

    #[test]
    fn detects_only_standalone_unsafe_token() {
        assert!(contains_unsafe_token("unsafe fn generated() {}"));
        assert!(!contains_unsafe_token("unsafe_code = \"forbid\""));
        assert!(!contains_unsafe_token("safe_without_unsafe_token"));
    }

    #[test]
    fn scans_build_scripts_outside_the_wire_src_directory() {
        let package_root = std::env::temp_dir().join(format!(
            "laneflow-road-editing-codegen-unsafe-boundary-{}",
            std::process::id()
        ));
        let source_root = package_root.join("src");
        fs::create_dir_all(&source_root).expect("temporary wire source directory");
        let generated_path = source_root.join("road-editing_generated.rs");
        fs::write(source_root.join("lib.rs"), "pub fn safe_wrapper() {}\n").expect("safe wrapper");
        fs::write(
            package_root.join("build.rs"),
            "unsafe fn hidden_target() {}\n",
        )
        .expect("unsafe build script");

        assert!(check_wire_rust_sources(&package_root, &generated_path).is_err());
        fs::remove_dir_all(&package_root).expect("remove temporary wire package");
    }
}
