//! FlatBuffers wire 生成物与受审计 `unsafe` 边界检查。
//!
//! 覆盖道路编辑（`LFRE`）与运行时快照（`LFRS`）两个私有 wire 家族；两者共用
//! 固定 flatc 版本、Rust canonical bytes clean-regeneration 比对、C++/C# probe。
//! unsafe 边界由 `check-wire-audit`（见 wire_audit.rs 模块文档）以 hermetic 编译
//! 与钉版断言闭合。

use std::collections::HashSet;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

pub(crate) const FLATBUFFERS_VERSION: &str = "25.12.19";
const GENERATED_HEADER: &[u8] =
    b"// automatically generated by the FlatBuffers compiler, do not modify\n// @generated\n";
const AUDITED_MMAP_MANIFEST_PATH: &str = "crates/laneflow-format-mmap/Cargo.toml";
const AUDITED_MMAP_PACKAGE_ROOT: &str = "crates/laneflow-format-mmap";
const AUDITED_MMAP_SOURCE_PATH: &str = "crates/laneflow-format-mmap/src/lib.rs";
const AUDITED_MMAP_EXPRESSION: &str = "unsafe { MmapOptions::new().len(expected).map(&self.file) }";

/// 一个私有 wire 家族的固定路径与命令面。
pub(crate) struct WireFamily {
    /// 中文标签，用于输出与错误信息。
    pub(crate) label: &'static str,
    /// 对应的 xtask 命令名。
    pub(crate) command: &'static str,
    /// schema 相对路径。
    pub(crate) schema_path: &'static str,
    /// checked-in Rust 生成物相对路径。
    pub(crate) checked_rust_path: &'static str,
    /// wire crate manifest 相对路径。
    pub(crate) wire_manifest_path: &'static str,
    /// wire crate 根相对路径。
    pub(crate) wire_package_root: &'static str,
    /// wire crate 包名（flatbuffers 钉版核对目标）。
    pub(crate) wire_package_name: &'static str,
    /// codegen 输出目录相对路径。
    pub(crate) output_root: &'static str,
    /// flatc 产出的 Rust 文件名。
    pub(crate) generated_rust_file: &'static str,
}

pub(crate) const ROAD_EDITING: WireFamily = WireFamily {
    label: "道路编辑",
    command: "check-road-editing-codegen",
    schema_path: "schemas/road-editing/v4/road-editing.fbs",
    checked_rust_path: "crates/laneflow-road-editing-wire/src/generated/road-editing_generated.rs",
    wire_manifest_path: "crates/laneflow-road-editing-wire/Cargo.toml",
    wire_package_root: "crates/laneflow-road-editing-wire",
    wire_package_name: "laneflow-road-editing-wire",
    output_root: "target/road-editing-codegen",
    generated_rust_file: "road-editing_generated.rs",
};

pub(crate) const RUNTIME_SNAPSHOT: WireFamily = WireFamily {
    label: "运行时快照",
    command: "check-runtime-snapshot-codegen",
    schema_path: "schemas/runtime-snapshot/v4/runtime-snapshot.fbs",
    checked_rust_path: "crates/laneflow-runtime-snapshot-wire/src/generated/runtime-snapshot_generated.rs",
    wire_manifest_path: "crates/laneflow-runtime-snapshot-wire/Cargo.toml",
    wire_package_root: "crates/laneflow-runtime-snapshot-wire",
    wire_package_name: "laneflow-runtime-snapshot-wire",
    output_root: "target/runtime-snapshot-codegen",
    generated_rust_file: "runtime-snapshot_generated.rs",
};

const WIRE_FAMILIES: [&WireFamily; 2] = [&ROAD_EDITING, &RUNTIME_SNAPSHOT];

pub(crate) fn run(family: &WireFamily, args: &[String]) -> Result<(), String> {
    let flatc = parse_flatc_path(family.command, args)?;
    let repository_root =
        std::env::current_dir().map_err(|error| format!("无法解析仓库根目录: {error}"))?;
    require_repository_root(&repository_root, family)?;
    check_unsafe_boundary(&repository_root)?;
    check_flatbuffers_runtime_version(&repository_root, family)?;
    check_flatc_version(&flatc)?;

    let output_root = repository_root.join(family.output_root);
    reset_output_root(&output_root)?;
    let rust_output = output_root.join("rust");
    let cpp_output = output_root.join("cpp");
    let csharp_output = output_root.join("csharp");
    for output in [&rust_output, &cpp_output, &csharp_output] {
        fs::create_dir_all(output).map_err(|error| {
            format!("无法创建 codegen 输出目录 `{}`: {error}", output.display())
        })?;
    }

    run_flatc(&flatc, "--rust", &rust_output, &repository_root, family)?;
    compare_generated_rust(
        &repository_root.join(family.checked_rust_path),
        &rust_output.join(family.generated_rust_file),
    )?;

    run_flatc(&flatc, "--cpp", &cpp_output, &repository_root, family)?;
    require_generated_extension(&cpp_output, "h")?;
    run_flatc(&flatc, "--csharp", &csharp_output, &repository_root, family)?;
    require_generated_extension(&csharp_output, "cs")?;

    println!(
        "{} codegen 已通过：{}；Rust canonical bytes clean，C++/C# probe 已生成，受审计 unsafe 边界已闭合",
        family.label,
        flatc.display()
    );
    Ok(())
}

fn parse_flatc_path(command: &str, args: &[String]) -> Result<PathBuf, String> {
    match args {
        [flag, path] if flag == "--flatc" && !path.is_empty() => Ok(PathBuf::from(path)),
        _ => Err(format!(
            "用法：cargo +1.98.0 run --locked -p xtask -- {command} --flatc <flatc-path>"
        )),
    }
}

fn require_repository_root(root: &Path, family: &WireFamily) -> Result<(), String> {
    for path in ["Cargo.toml", family.schema_path, family.checked_rust_path] {
        if !root.join(path).is_file() {
            return Err(format!("必须从 LaneFlow 仓库根目录运行；缺少 `{path}`"));
        }
    }
    Ok(())
}

fn check_flatc_version(flatc: &Path) -> Result<(), String> {
    let output = Command::new(flatc)
        .arg("--version")
        .output()
        .map_err(|error| format!("无法执行 `{}`: {error}", flatc.display()))?;
    if !output.status.success() {
        return Err(format!(
            "`{} --version` 失败，exit={}",
            flatc.display(),
            output.status
        ));
    }
    let stdout = String::from_utf8(output.stdout)
        .map_err(|error| format!("flatc version 输出不是 UTF-8: {error}"))?;
    let actual = stdout.trim();
    let expected = format!("flatc version {FLATBUFFERS_VERSION}");
    if actual != expected {
        return Err(format!(
            "flatc 版本不匹配：预期 `{expected}`，实际 `{actual}`"
        ));
    }
    Ok(())
}

fn check_flatbuffers_runtime_version(
    repository_root: &Path,
    family: &WireFamily,
) -> Result<(), String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .current_dir(repository_root)
        .args([
            "metadata",
            "--format-version",
            "1",
            "--no-deps",
            "--locked",
            "--manifest-path",
            family.wire_manifest_path,
        ])
        .output()
        .map_err(|error| format!("无法读取 wire crate Cargo metadata: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "`cargo metadata --manifest-path {}` 失败，exit={}，stderr={}",
            family.wire_manifest_path,
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    require_flatbuffers_runtime_pin(&output.stdout, family.wire_package_name)
}

fn require_flatbuffers_runtime_pin(metadata: &[u8], wire_package_name: &str) -> Result<(), String> {
    let metadata: serde_json::Value = serde_json::from_slice(metadata)
        .map_err(|error| format!("Cargo metadata 不是有效 JSON: {error}"))?;
    let packages = metadata
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "Cargo metadata 缺少 packages 数组".to_string())?;
    let wire_package = packages
        .iter()
        .find(|package| {
            package.get("name").and_then(serde_json::Value::as_str) == Some(wire_package_name)
        })
        .ok_or_else(|| format!("Cargo metadata 缺少 {wire_package_name} package"))?;
    let dependencies = wire_package
        .get("dependencies")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "wire package metadata 缺少 dependencies 数组".to_string())?;
    let expected = format!("={FLATBUFFERS_VERSION}");
    let mut runtime_count = 0;
    for runtime in dependencies.iter().filter(|dependency| {
        dependency.get("name").and_then(serde_json::Value::as_str) == Some("flatbuffers")
    }) {
        runtime_count += 1;
        let actual = runtime
            .get("req")
            .and_then(serde_json::Value::as_str)
            .ok_or_else(|| "flatbuffers runtime metadata 缺少版本约束".to_string())?;
        if actual != expected {
            let target = runtime
                .get("target")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("all targets");
            return Err(format!(
                "flatbuffers runtime 版本不匹配：target `{target}` 预期精确约束 `{expected}`，实际 `{actual}`"
            ));
        }
    }
    if runtime_count == 0 {
        return Err("wire package 缺少 flatbuffers runtime 依赖".to_string());
    }
    Ok(())
}

fn reset_output_root(output_root: &Path) -> Result<(), String> {
    if output_root.exists() {
        fs::remove_dir_all(output_root).map_err(|error| {
            format!(
                "无法清理固定 codegen 输出目录 `{}`: {error}",
                output_root.display()
            )
        })?;
    }
    Ok(())
}

fn run_flatc(
    flatc: &Path,
    language: &str,
    output: &Path,
    repository_root: &Path,
    family: &WireFamily,
) -> Result<(), String> {
    let status = Command::new(flatc)
        .current_dir(repository_root)
        .arg(language)
        .arg("-o")
        .arg(output)
        .arg(family.schema_path)
        .status()
        .map_err(|error| format!("无法执行 `{}` {language}: {error}", flatc.display()))?;
    if !status.success() {
        return Err(format!(
            "`{} {language} -o {} {}` 失败，exit={status}",
            flatc.display(),
            output.display(),
            family.schema_path
        ));
    }
    Ok(())
}

fn compare_generated_rust(checked: &Path, regenerated: &Path) -> Result<(), String> {
    let checked_bytes = fs::read(checked).map_err(|error| {
        format!(
            "无法读取 checked-in Rust 生成物 `{}`: {error}",
            checked.display()
        )
    })?;
    let regenerated_bytes = fs::read(regenerated).map_err(|error| {
        format!(
            "flatc 未生成预期 Rust 文件 `{}`: {error}",
            regenerated.display()
        )
    })?;
    let checked_canonical = canonical_generated_source(&checked_bytes)?;
    let regenerated_canonical = canonical_generated_source(&regenerated_bytes)?;

    if !checked_canonical.starts_with(GENERATED_HEADER) {
        return Err(format!(
            "checked-in Rust 生成物 `{}` 缺少固定 generated header",
            checked.display()
        ));
    }
    if checked_canonical != regenerated_canonical {
        let first_difference = checked_canonical
            .iter()
            .zip(&regenerated_canonical)
            .position(|(left, right)| left != right)
            .unwrap_or(checked_canonical.len().min(regenerated_canonical.len()));
        return Err(format!(
            "Rust 生成物不是 clean regeneration：canonical byte offset {first_difference} 首次不同，checked={} bytes，regenerated={} bytes；请使用固定 flatc 重新生成并提交 `{}`",
            checked_canonical.len(),
            regenerated_canonical.len(),
            checked.display()
        ));
    }
    Ok(())
}

fn canonical_generated_source(bytes: &[u8]) -> Result<Vec<u8>, String> {
    let mut canonical = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        match bytes[index] {
            b'\r' => {
                if bytes.get(index + 1) != Some(&b'\n') {
                    return Err(format!("生成物在 byte offset {index} 含有非 CRLF 的裸 CR"));
                }
                canonical.push(b'\n');
                index += 2;
            }
            byte => {
                canonical.push(byte);
                index += 1;
            }
        }
    }
    Ok(canonical)
}

fn require_generated_extension(root: &Path, extension: &str) -> Result<(), String> {
    let mut files = Vec::new();
    collect_files(root, &mut files)?;
    if files.iter().any(|path| {
        path.extension() == Some(OsStr::new(extension))
            && fs::metadata(path).is_ok_and(|metadata| metadata.len() > 0)
    }) {
        return Ok(());
    }
    Err(format!(
        "flatc probe `{}` 未产生非空 .{extension} 文件",
        root.display()
    ))
}

fn check_unsafe_boundary(repository_root: &Path) -> Result<(), String> {
    let workspace_manifest = fs::read_to_string(repository_root.join("Cargo.toml"))
        .map_err(|error| format!("无法读取 workspace Cargo.toml: {error}"))?;
    if !toml_has_value(
        &workspace_manifest,
        "workspace.lints.rust",
        "unsafe_code",
        "forbid",
    ) {
        return Err(
            "workspace 必须保持 `[workspace.lints.rust] unsafe_code = \"forbid\"`".to_string(),
        );
    }

    let mut wire_manifest_paths = HashSet::new();
    for family in WIRE_FAMILIES {
        let wire_manifest = fs::read_to_string(repository_root.join(family.wire_manifest_path))
            .map_err(|error| format!("无法读取 `{}`: {error}", family.wire_manifest_path))?;
        if !toml_has_value(&wire_manifest, "lints.rust", "unsafe_code", "allow") {
            return Err(format!(
                "`{}` 必须保持 generated-only `unsafe_code = \"allow\"` 边界",
                family.wire_manifest_path
            ));
        }
        let canonical = repository_root
            .join(family.wire_manifest_path)
            .canonicalize()
            .map_err(|error| format!("无法解析 `{}`: {error}", family.wire_manifest_path))?;
        wire_manifest_paths.insert(canonical);
    }
    let audited_mmap_manifest = repository_root
        .join(AUDITED_MMAP_MANIFEST_PATH)
        .canonicalize()
        .map_err(|error| {
            format!("无法解析 `{AUDITED_MMAP_MANIFEST_PATH}` 的受审计 mmap 边界: {error}")
        })?;

    let manifests = workspace_manifest_paths(repository_root)?;
    for manifest in manifests {
        let manifest = manifest
            .canonicalize()
            .map_err(|error| format!("无法解析 `{}`: {error}", manifest.display()))?;
        if wire_manifest_paths.contains(&manifest) {
            continue;
        }
        let text = fs::read_to_string(&manifest)
            .map_err(|error| format!("无法读取 `{}`: {error}", manifest.display()))?;
        if manifest == audited_mmap_manifest {
            if !toml_has_value(&text, "lints.rust", "unsafe_code", "allow") {
                return Err(format!(
                    "受审计 mmap package 必须保持 crate 级 `unsafe_code = \"allow\"` 登记例外：`{}`",
                    manifest.display()
                ));
            }
            continue;
        }
        if toml_has_value(&text, "lints.rust", "unsafe_code", "allow") {
            return Err(format!(
                "generated 路径外不得放宽 unsafe lint：`{}`",
                manifest.display()
            ));
        }
        if !toml_has_value(&text, "lints", "workspace", "true") {
            return Err(format!(
                "手写 workspace package 必须继承 `unsafe_code = \"forbid\"`：`{}`",
                manifest.display()
            ));
        }
    }

    for family in WIRE_FAMILIES {
        let generated_path = repository_root.join(family.checked_rust_path);
        check_wire_rust_sources(
            &repository_root.join(family.wire_package_root),
            &generated_path,
        )?;
    }
    check_audited_mmap_sources(repository_root)?;
    Ok(())
}

pub(crate) fn check_audited_mmap_sources(repository_root: &Path) -> Result<(), String> {
    let package_root = repository_root.join(AUDITED_MMAP_PACKAGE_ROOT);
    let allowed_source = repository_root.join(AUDITED_MMAP_SOURCE_PATH);
    let mut sources = Vec::new();
    collect_extension_files(&package_root, OsStr::new("rs"), &mut sources)?;
    for source in sources {
        let text = fs::read_to_string(&source)
            .map_err(|error| format!("无法读取 `{}`: {error}", source.display()))?;
        // rustc 只有两条路径加载 .rs 扫描面之外的源码：`#[path = "..."]` 模块
        // 属性与 `include!(...)` 宏。两者皆禁，保证 .rs 全集即编译器可达源码全集，
        // 非 .rs 载荷（如 `#[path = "payload.txt"]`）无处挂接。
        if contains_source_loading_directive(&text) {
            return Err(format!(
                "受审计 mmap package 内禁止 `#[path]` 模块属性与 `include!` 宏（防止加载 .rs 扫描面之外的源码）：`{}`",
                source.display()
            ));
        }
        // 注释与字面量内容不参与编译，计数在 strip 后的代码文本上进行：
        // 文档注释可以提及 unsafe 语义，字符串断言不再误报。
        let code = strip_non_code(&text);
        // `cfg_attr(..., path = "...")` 可包裹 path 属性逃逸上面的直接形态
        // 检测；本 crate 没有任何合法 cfg_attr 需求，全面禁用。
        if contains_cfg_attr_token(&code) {
            return Err(format!(
                "受审计 mmap package 内禁止 `cfg_attr`（其可包裹 path 属性逃逸源码加载检测）：`{}`",
                source.display()
            ));
        }
        // 词法精确兜底：任何真实 path 属性（含 `# [` trivia 变体）一律拒绝，
        // 编译器可达源码全集收敛为包内 .rs 扫描面。
        check_path_attribute_values(
            &text,
            &format!("受审计 mmap source `{}`", source.display()),
            PathAttributePolicy::RejectAll,
        )?;
        // macro_rules 元变量间接（`$m:ident` → `load!(include)` 展开为
        // `include!`）可把加载指令藏出上面的文本扫描；本 crate 无合法宏定义
        // 需求，禁 `macro_rules!` 定义即闭合该间接层。宏调用不受限。不另禁
        // `macro` 定义：其需 #![feature]，stable 工具链编译即失败，自闭合。
        if contains_bare_token(&code, "macro_rules") {
            return Err(format!(
                "受审计 mmap package 内禁止 `macro_rules!` 宏定义（元变量间接可把 include! 藏出文本扫描）：`{}`",
                source.display()
            ));
        }
        if source == allowed_source {
            if code.matches("#![allow(unsafe_code)]").count() != 1
                || code.matches(AUDITED_MMAP_EXPRESSION).count() != 1
                || count_unsafe_tokens(&code) != 1
            {
                return Err(format!(
                    "受审计 mmap source 只能包含一次模块级 lint 例外和一次固定只读映射调用：`{}`",
                    source.display()
                ));
            }
            continue;
        }
        if contains_unsafe_token(&code) || code.contains("allow(unsafe_code)") {
            return Err(format!(
                "受审计 mmap source 外不得包含 unsafe：`{}`",
                source.display()
            ));
        }
    }
    Ok(())
}

/// 从 `/*` 起始位置跳过（可嵌套）块注释，返回注释结束之后第一个字节的下标。
fn skip_block_comment(text: &str, start: usize) -> usize {
    let bytes = text.as_bytes();
    let mut depth = 1usize;
    let mut cursor = start + 2;
    while cursor < bytes.len() && depth > 0 {
        if text[cursor..].starts_with("/*") {
            depth += 1;
            cursor += 2;
        } else if text[cursor..].starts_with("*/") {
            depth -= 1;
            cursor += 2;
        } else {
            cursor += text[cursor..].chars().next().map_or(1, char::len_utf8);
        }
    }
    cursor
}

/// 识别 `include!` 宏调用（token 级：标识符边界 + `!`，其间可夹空白与
/// 注释 trivia——rustc 词法允许）。`include_str!` / `include_bytes!`
/// 只加载数据不加载代码，豁免。
pub(crate) fn contains_include_macro(text: &str) -> bool {
    for (index, token) in text.match_indices("include") {
        let before = text[..index].chars().next_back();
        if before.is_some_and(is_identifier_character) {
            continue;
        }
        let rest = &text[index + token.len()..];
        if rest.chars().next().is_some_and(is_identifier_character) {
            // include_str! / include_bytes! 等标识符延续。
            continue;
        }
        if text[skip_trivia(text, index + token.len())..].starts_with('!') {
            return true;
        }
    }
    false
}

/// 识别源码加载指令：`#[path]` 属性与 `include!` 宏调用。token 级扫描——
/// `#[` 与 `path` 之间、`include` 与 `!` 之间的空白在 rustc 词法中合法，
/// 逐一容忍；`include_str!` / `include_bytes!` 只加载数据不加载代码，豁免。
fn contains_source_loading_directive(text: &str) -> bool {
    for (index, _) in text.match_indices("#[") {
        let rest = text[index + 2..].trim_start();
        if rest.starts_with("path")
            && rest[4..]
                .chars()
                .next()
                .is_none_or(|character| !is_identifier_character(character))
        {
            return true;
        }
    }
    contains_include_macro(text)
}

/// 识别 strip 后代码中的裸 `name` token（前后均非标识符字符）。
pub(crate) fn contains_bare_token(code: &str, name: &str) -> bool {
    code.match_indices(name).any(|(index, token)| {
        let before = code[..index].chars().next_back();
        let after = code[index + token.len()..].chars().next();
        !before.is_some_and(is_identifier_character) && !after.is_some_and(is_identifier_character)
    })
}

/// 识别 strip 后代码中的裸 `cfg_attr` token。mmap 例外 crate 全面禁用
/// `cfg_attr`：`#[cfg_attr(..., path = "...")]` 可包裹 path 属性，逃逸
/// 直接形态的源码加载指令检测。
pub(crate) fn contains_cfg_attr_token(code: &str) -> bool {
    contains_bare_token(code, "cfg_attr")
}

/// 识别 macro_rules 转写器里的元变量调用（`$m!`，其间可夹 trivia）：宏
/// 调用名被元变量间接后，`include!` 等源码加载指令可藏出文本扫描。
/// forbid 成员的 `macro_rules!` 本身合法，禁令只落在元变量调用位置。
/// `$crate`（后跟 `::`）、重复结构 `$( ... )*`、元变量类型标注
/// `$x:expr` 均不匹配。输入应为 strip 后的代码文本（字面量已剥除）。
pub(crate) fn contains_metavariable_invocation(code: &str) -> bool {
    let bytes = code.as_bytes();
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'$' {
            let mut end = index + 1;
            while end < bytes.len() {
                let Some(character) = code[end..].chars().next() else {
                    break;
                };
                if !is_identifier_character(character) {
                    break;
                }
                end += character.len_utf8();
            }
            if end > index + 1 && code[skip_trivia(code, end)..].starts_with('!') {
                return true;
            }
        }
        index += 1;
    }
    false
}

/// 识别 strip 后代码中的裸 `include` 标识符（任意上下文）。forbid 成员内
/// `include!` 已全面禁止；宏展开无法拼出新标识符，因此禁绝裸 `include`
/// 标识符即闭合一切经元变量碎片拼装的间接形态——宏体内的
/// `include $bang ($p)` 与调用点的 `load!(include, ...)` 都必然在源码中
/// 留下该标识符。`include_str!` / `include_bytes!` 是不同标识符，不受影响。
pub(crate) fn contains_include_identifier(code: &str) -> bool {
    contains_bare_token(code, "include")
}

pub(crate) fn workspace_manifest_paths(repository_root: &Path) -> Result<Vec<PathBuf>, String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .current_dir(repository_root)
        .args([
            "metadata",
            "--format-version",
            "1",
            "--no-deps",
            "--locked",
            "--manifest-path",
            "Cargo.toml",
        ])
        .output()
        .map_err(|error| format!("无法读取 workspace Cargo metadata: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "`cargo metadata --manifest-path Cargo.toml` 失败，exit={}，stderr={}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    parse_workspace_manifest_paths(&output.stdout)
}

fn parse_workspace_manifest_paths(metadata: &[u8]) -> Result<Vec<PathBuf>, String> {
    let metadata: serde_json::Value = serde_json::from_slice(metadata)
        .map_err(|error| format!("Cargo metadata 不是有效 JSON: {error}"))?;
    let members = metadata
        .get("workspace_members")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "Cargo metadata 缺少 workspace_members 数组".to_string())?;
    let packages = metadata
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "Cargo metadata 缺少 packages 数组".to_string())?;
    let mut manifests = Vec::with_capacity(members.len());
    for member in members {
        let member = member
            .as_str()
            .ok_or_else(|| "Cargo metadata workspace member 不是字符串".to_string())?;
        let package = packages
            .iter()
            .find(|package| package.get("id").and_then(serde_json::Value::as_str) == Some(member))
            .ok_or_else(|| format!("Cargo metadata 缺少 workspace member package `{member}`"))?;
        let manifest = package
            .get("manifest_path")
            .and_then(serde_json::Value::as_str)
            .ok_or_else(|| format!("workspace package `{member}` 缺少 manifest_path"))?;
        manifests.push(PathBuf::from(manifest));
    }
    manifests.sort_unstable();
    Ok(manifests)
}

fn check_wire_rust_sources(package_root: &Path, generated_path: &Path) -> Result<(), String> {
    let mut wire_sources = Vec::new();
    collect_extension_files(package_root, OsStr::new("rs"), &mut wire_sources)?;
    for source in wire_sources {
        if source == generated_path {
            continue;
        }
        let text = fs::read_to_string(&source)
            .map_err(|error| format!("无法读取 `{}`: {error}", source.display()))?;
        if contains_unsafe_token(&text) || text.contains("allow(unsafe_code)") {
            return Err(format!(
                "wire package 的手写 Rust 路径不得包含 unsafe：`{}`",
                source.display()
            ));
        }
    }
    Ok(())
}

fn toml_has_value(text: &str, section: &str, key: &str, expected: &str) -> bool {
    let mut current_section = "";
    for raw_line in text.lines() {
        let line = raw_line.split('#').next().unwrap_or_default().trim();
        if line.starts_with('[') && line.ends_with(']') {
            current_section = line.trim_matches(&['[', ']'][..]).trim();
            continue;
        }
        if current_section != section {
            continue;
        }
        let Some((actual_key, actual_value)) = line.split_once('=') else {
            continue;
        };
        if actual_key.trim() == key && actual_value.trim().trim_matches('"') == expected {
            return true;
        }
    }
    false
}

/// path 属性目标的审计策略。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum PathAttributePolicy {
    /// 任何真实 path 属性都拒绝：mmap 例外 crate 的源码全集必须就是包内
    /// .rs 扫描面，`mod` 外挂接一律禁绝。
    RejectAll,
    /// 目标必须是以 `.rs` 结尾的包内相对路径（无 `..`、无盘符/绝对前缀、
    /// 无反斜杠）：forbid 成员的合法用法（tests 指向包内 support 文件）
    /// 保留，越界加载 fail closed。无 `..` 且无绝对前缀的相对路径不可能
    /// 逃出 package 根目录。
    PackageRelativeRs,
}

/// 校验源码中全部 path 属性（直接 `#[path = "..."]` 与 `cfg_attr(...)` 包裹
/// 形态）的目标值。与 [`strip_non_code`] 同构的逐字节状态机：注释与
/// 字符串/字符字面量整体跳过，文档与测试固件里的 `#[path]` 字样不触发误判；
/// 只有编译器真实可达的属性被解析。`#[path]` 只接受立即字符串值是 rustc
/// 语法约束，因此 `path` 后未紧跟 `= <字面量>` 的必然不是真实属性，跳过。
pub(crate) fn check_path_attribute_values(
    text: &str,
    owner: &str,
    policy: PathAttributePolicy,
) -> Result<(), String> {
    let bytes = text.as_bytes();
    let mut index = 0;
    while index < bytes.len() {
        let rest = &text[index..];
        if rest.starts_with("//") {
            index += rest.find('\n').unwrap_or(rest.len());
            continue;
        }
        if rest.starts_with("/*") {
            index = skip_block_comment(text, index);
            continue;
        }
        if let Some((prefix_width, hashes)) = raw_string_prefix(rest) {
            index = skip_raw_string(text, index + prefix_width, hashes);
            continue;
        }
        if rest.starts_with('"') {
            index = skip_escaped_literal(text, index + 1, '"');
            continue;
        }
        if rest.starts_with("b\"") || rest.starts_with("c\"") {
            index = skip_escaped_literal(text, index + 2, '"');
            continue;
        }
        if rest.starts_with('\'')
            && let Some(width) = char_literal_width(rest)
        {
            index += width;
            continue;
        }
        if rest.starts_with('#') {
            // rustc 允许 `#` 与 `[`（内层属性还有 `!`）之间夹 trivia。
            let mut cursor = skip_trivia(text, index + 1);
            if text[cursor..].starts_with('!') {
                cursor = skip_trivia(text, cursor + 1);
            }
            if text[cursor..].starts_with('[') {
                index = check_attribute_region(text, cursor + 1, owner, policy)?;
                continue;
            }
        }
        let character = rest.chars().next().expect("non-empty rest");
        index += character.len_utf8();
    }
    Ok(())
}

/// 从 `[` 之后扫描一个属性区域，按分隔符配对走到闭合 `]`；识别区域内全部
/// 裸 `path` 标识符 + `=` + 字符串字面量形态并校验目标值（cfg_attr 包裹形态
/// 只是区域内的嵌套，天然覆盖）。返回属性区域之后的下标。区域截断或分隔符
/// 不配对时 fail closed——合法 Rust 属性的分隔符必然配对。
fn check_attribute_region(
    text: &str,
    mut index: usize,
    owner: &str,
    policy: PathAttributePolicy,
) -> Result<usize, String> {
    let bytes = text.as_bytes();
    let mut stack = vec![b']'];
    while index < bytes.len() {
        let rest = &text[index..];
        if rest.starts_with("//") {
            index += rest.find('\n').unwrap_or(rest.len());
            continue;
        }
        if rest.starts_with("/*") {
            index = skip_block_comment(text, index);
            continue;
        }
        if let Some((prefix_width, hashes)) = raw_string_prefix(rest) {
            index = skip_raw_string(text, index + prefix_width, hashes);
            continue;
        }
        if rest.starts_with('"') {
            index = skip_escaped_literal(text, index + 1, '"');
            continue;
        }
        if rest.starts_with('\'')
            && let Some(width) = char_literal_width(rest)
        {
            index += width;
            continue;
        }
        match bytes[index] {
            b'[' => stack.push(b']'),
            b'(' => stack.push(b')'),
            b'{' => stack.push(b'}'),
            byte @ (b']' | b')' | b'}') => {
                if stack.pop() != Some(byte) {
                    return Err(format!(
                        "{owner} 的属性区域分隔符不配对，无法静态审计，fail closed"
                    ));
                }
                if stack.is_empty() {
                    return Ok(index + 1);
                }
            }
            _ => {
                if is_bare_ident_at(text, index, "path") {
                    match scan_path_value(text, index + "path".len()) {
                        PathValueScan::NotAttribute => {}
                        PathValueScan::Value(end, value) => {
                            check_path_value(&value, owner, policy)?;
                            index = end;
                            continue;
                        }
                    }
                }
            }
        }
        index += text[index..].chars().next().map_or(1, char::len_utf8);
    }
    Err(format!(
        "{owner} 的属性区域未闭合，无法静态审计，fail closed"
    ))
}

/// `index` 处是否以裸标识符 `name` 起始（前后均非标识符字符）。
fn is_bare_ident_at(text: &str, index: usize, name: &str) -> bool {
    let rest = &text[index..];
    if !rest.starts_with(name) {
        return false;
    }
    let before = text[..index].chars().next_back();
    let after = rest[name.len()..].chars().next();
    !before.is_some_and(is_identifier_character) && !after.is_some_and(is_identifier_character)
}

enum PathValueScan {
    /// `path` 后未紧跟 `= <字符串字面量>`：不是真实 path 属性，跳过。
    NotAttribute,
    /// （字面量结束后下标, 字面量原始内容）。
    Value(usize, String),
}

/// 从 `path` 之后解析 `= <字符串字面量>`（普通与 raw string 两种形态），
/// 容忍其间的空白与注释。
fn scan_path_value(text: &str, mut index: usize) -> PathValueScan {
    index = skip_trivia(text, index);
    if !text[index..].starts_with('=') {
        return PathValueScan::NotAttribute;
    }
    index = skip_trivia(text, index + 1);
    let rest = &text[index..];
    if let Some((prefix_width, hashes)) = raw_string_prefix(rest) {
        let content_start = index + prefix_width;
        let end = skip_raw_string(text, content_start, hashes);
        let content_end = end.saturating_sub(1 + hashes);
        return PathValueScan::Value(end, text[content_start..content_end].to_string());
    }
    if rest.starts_with('"') {
        let end = skip_escaped_literal(text, index + 1, '"');
        return PathValueScan::Value(end, text[index + 1..end.saturating_sub(1)].to_string());
    }
    PathValueScan::NotAttribute
}

/// 跳过空白与注释（trivia）。
fn skip_trivia(text: &str, mut index: usize) -> usize {
    loop {
        let rest = &text[index..];
        let trimmed = rest.trim_start();
        index += rest.len() - trimmed.len();
        let rest = &text[index..];
        if rest.starts_with("//") {
            index += rest.find('\n').unwrap_or(rest.len());
            continue;
        }
        if rest.starts_with("/*") {
            index = skip_block_comment(text, index);
            continue;
        }
        return index;
    }
}

fn check_path_value(value: &str, owner: &str, policy: PathAttributePolicy) -> Result<(), String> {
    let violation = match policy {
        PathAttributePolicy::RejectAll => true,
        PathAttributePolicy::PackageRelativeRs => {
            !value.ends_with(".rs")
                || value.contains("..")
                || value.contains([':', '\\'])
                || value.starts_with('/')
        }
    };
    if violation {
        let rule = match policy {
            PathAttributePolicy::RejectAll => {
                "本 crate 禁止任何 path 属性（`mod` 外挂接逃逸 .rs 扫描面）"
            }
            PathAttributePolicy::PackageRelativeRs => {
                "path 属性目标只允许以 .rs 结尾的包内相对路径（无 `..`、无盘符/绝对前缀、无反斜杠）"
            }
        };
        return Err(format!(
            "{owner} 的 path 属性目标 `{value}` 不被允许：{rule}，防止加载文本扫描面之外的源码"
        ));
    }
    Ok(())
}

fn contains_unsafe_token(text: &str) -> bool {
    count_unsafe_tokens(text) != 0
}

pub(crate) fn count_unsafe_tokens(text: &str) -> usize {
    text.match_indices("unsafe")
        .filter(|&(index, token)| {
            let before = text[..index].chars().next_back();
            let after = text[index + token.len()..].chars().next();
            !before.is_some_and(is_identifier_character)
                && !after.is_some_and(is_identifier_character)
        })
        .count()
}

/// 把 Rust 源码中的注释与字符串/字节/C/字符字面量整体替换为空白，保留其余
/// token 文本。注释/字面量内容不参与编译，strip 后的文本用于"与 cfg 无关"
/// 的 unsafe token 扫描：无论代码藏在哪个 cfg 分支、profile 或平台后面，
/// `unsafe` 关键字都必须以源码 token 形态出现。字面量内容含 `unsafe` 字样
/// （测试断言字符串等）不再误报。
///
/// 逐字节状态机：UTF-8 多字节序列的续字节均 >= 0x80，不与任何 ASCII 定界符
/// 冲突，Normal 状态下原样拷贝。
pub(crate) fn strip_non_code(text: &str) -> String {
    let bytes = text.as_bytes();
    let mut output = String::with_capacity(text.len());
    let mut index = 0;
    while index < bytes.len() {
        let rest = &text[index..];
        if rest.starts_with("//") {
            index += rest.find('\n').unwrap_or(bytes.len());
            output.push(' ');
            continue;
        }
        if rest.starts_with("/*") {
            index = skip_block_comment(text, index);
            output.push(' ');
            continue;
        }
        if let Some((prefix_width, hashes)) = raw_string_prefix(rest) {
            index = skip_raw_string(text, index + prefix_width, hashes);
            output.push(' ');
            continue;
        }
        if rest.starts_with('"') {
            index = skip_escaped_literal(text, index + 1, '"');
            output.push(' ');
            continue;
        }
        if rest.starts_with("b\"") || rest.starts_with("c\"") {
            index = skip_escaped_literal(text, index + 2, '"');
            output.push(' ');
            continue;
        }
        if rest.starts_with('\'') {
            match char_literal_width(rest) {
                Some(width) => {
                    index += width;
                    output.push(' ');
                }
                // 生命周期：不是字面量，引号本身照常输出。
                None => {
                    output.push('\'');
                    index += 1;
                }
            }
            continue;
        }
        let character = rest.chars().next().expect("non-empty rest");
        output.push(character);
        index += character.len_utf8();
    }
    output
}

/// 识别 raw string 前缀 `r"` / `r#"…"#` / `br…` / `cr…`，返回（前缀字节
/// 宽度, `#` 数量）。合法 Rust 中不存在"标识符紧挨字符串字面量"的形态
/// （`r"x"` 本身就是 raw string 语法），逐字节推进无需回看前一 token。
fn raw_string_prefix(rest: &str) -> Option<(usize, usize)> {
    for prefix in ["br", "cr", "r"] {
        if let Some(after) = rest.strip_prefix(prefix)
            && let Some(hashes) = raw_string_hashes(after)
        {
            return Some((prefix.len() + hashes + 1, hashes));
        }
    }
    None
}

/// 在 `r` / `br` / `cr` 之后识别 `#*` + `"`；返回 `#` 数量。
fn raw_string_hashes(after_prefix: &str) -> Option<usize> {
    let hashes = after_prefix
        .bytes()
        .take_while(|byte| *byte == b'#')
        .count();
    if after_prefix[hashes..].starts_with('"') {
        Some(hashes)
    } else {
        None
    }
}

/// 从开引号之后跳过 raw string 直至闭合的 `"` + `#`×hashes。
fn skip_raw_string(text: &str, cursor: usize, hashes: usize) -> usize {
    let closing: String = std::iter::once('"')
        .chain(std::iter::repeat_n('#', hashes))
        .collect();
    text[cursor..]
        .find(&closing)
        .map_or(text.len(), |found| cursor + found + closing.len())
}

/// 从开定界符之后跳过带 `\\` 转义的字面量直至闭合定界符。
fn skip_escaped_literal(text: &str, mut cursor: usize, delimiter: char) -> usize {
    let bytes = text.as_bytes();
    let delimiter = delimiter as u8;
    while cursor < bytes.len() {
        match bytes[cursor] {
            b'\\' => cursor += 2,
            byte if byte == delimiter => return cursor + 1,
            _ => cursor += text[cursor..].chars().next().map_or(1, char::len_utf8),
        }
    }
    text.len()
}

/// 判定 `'` 起始的字符字面量宽度（含两个引号）；生命周期返回 None。
/// 规则（rustc 词法同）：`'\` 必为字符字面量（转义）；`'c'` 单字符后跟
/// 闭合引号为字符字面量；其余（`'a`、`'static`）为生命周期。
fn char_literal_width(rest: &str) -> Option<usize> {
    let after_quote = &rest[1..];
    if after_quote.starts_with('\\') {
        // 从反斜杠位置起跳，让转义对（含 '\''）被整体跳过。
        return Some(skip_escaped_literal(rest, 1, '\''));
    }
    let character = after_quote.chars().next()?;
    let width = 1 + character.len_utf8();
    rest[width..].starts_with('\'').then_some(width + 1)
}

pub(crate) fn is_identifier_character(character: char) -> bool {
    character == '_' || character.is_alphanumeric()
}

fn collect_files(root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if !root.is_dir() {
        return Err(format!("目录不存在：`{}`", root.display()));
    }
    for entry in
        fs::read_dir(root).map_err(|error| format!("无法枚举 `{}`: {error}", root.display()))?
    {
        let path = entry
            .map_err(|error| format!("无法读取 `{}` 的目录项: {error}", root.display()))?
            .path();
        if path.is_dir() {
            collect_files(&path, files)?;
        } else if path.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

pub(crate) fn collect_extension_files(
    root: &Path,
    extension: &OsStr,
    files: &mut Vec<PathBuf>,
) -> Result<(), String> {
    let mut candidates = Vec::new();
    collect_files(root, &mut candidates)?;
    files.extend(
        candidates
            .into_iter()
            .filter(|path| path.extension() == Some(extension)),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_exact_flatc_argument() {
        assert_eq!(
            parse_flatc_path(
                "check-road-editing-codegen",
                &["--flatc".to_string(), "tools/flatc".to_string()]
            ),
            Ok(PathBuf::from("tools/flatc"))
        );
        assert!(parse_flatc_path("check-road-editing-codegen", &[]).is_err());
        assert!(
            parse_flatc_path("check-runtime-snapshot-codegen", &["--flatc".to_string()]).is_err()
        );
        assert!(
            parse_flatc_path(
                "check-road-editing-codegen",
                &[
                    "--flatc".to_string(),
                    "flatc".to_string(),
                    "extra".to_string()
                ]
            )
            .is_err()
        );
    }

    #[test]
    fn canonicalizes_only_line_endings() {
        assert_eq!(
            canonical_generated_source(b"a\r\nb\n"),
            Ok(b"a\nb\n".to_vec())
        );
        assert!(canonical_generated_source(b"a\rb").is_err());
    }

    #[test]
    fn reads_exact_toml_lint_values() {
        let manifest = "[lints]\nworkspace = true\n\n[lints.rust]\nunsafe_code = \"allow\"\n";
        assert!(toml_has_value(manifest, "lints", "workspace", "true"));
        assert!(toml_has_value(
            manifest,
            "lints.rust",
            "unsafe_code",
            "allow"
        ));
        assert!(!toml_has_value(
            manifest,
            "workspace.lints.rust",
            "unsafe_code",
            "forbid"
        ));
    }

    #[test]
    fn derives_every_manifest_from_workspace_membership() {
        let metadata = br#"{
            "workspace_members": ["wire 0.0.0", "example 0.0.0"],
            "packages": [
                {"id": "wire 0.0.0", "manifest_path": "E:/repo/crates/wire/Cargo.toml"},
                {"id": "example 0.0.0", "manifest_path": "E:/repo/examples/foo/Cargo.toml"},
                {"id": "outside 0.0.0", "manifest_path": "E:/outside/Cargo.toml"}
            ]
        }"#;

        assert_eq!(
            parse_workspace_manifest_paths(metadata).unwrap(),
            [
                PathBuf::from("E:/repo/crates/wire/Cargo.toml"),
                PathBuf::from("E:/repo/examples/foo/Cargo.toml"),
            ]
        );
    }

    #[test]
    fn requires_runtime_version_to_match_flatc() {
        let matching = br#"{
            "packages": [{
                "name": "laneflow-road-editing-wire",
                "dependencies": [{"name": "flatbuffers", "req": "=25.12.19"}]
            }]
        }"#;
        assert_eq!(
            require_flatbuffers_runtime_pin(matching, "laneflow-road-editing-wire"),
            Ok(())
        );
        assert!(
            require_flatbuffers_runtime_pin(matching, "laneflow-runtime-snapshot-wire").is_err()
        );

        let mismatched = br#"{
            "packages": [{
                "name": "laneflow-runtime-snapshot-wire",
                "dependencies": [{"name": "flatbuffers", "req": "=25.9.23"}]
            }]
        }"#;
        assert!(
            require_flatbuffers_runtime_pin(mismatched, "laneflow-runtime-snapshot-wire").is_err()
        );
    }

    #[test]
    fn requires_every_target_runtime_version_to_match_flatc() {
        let matching = br#"{
            "packages": [{
                "name": "laneflow-road-editing-wire",
                "dependencies": [
                    {"name": "flatbuffers", "req": "=25.12.19", "target": "cfg(not(windows))"},
                    {"name": "flatbuffers", "req": "=25.12.19", "target": "cfg(windows)"}
                ]
            }]
        }"#;
        assert_eq!(
            require_flatbuffers_runtime_pin(matching, "laneflow-road-editing-wire"),
            Ok(())
        );

        let mismatched = br#"{
            "packages": [{
                "name": "laneflow-road-editing-wire",
                "dependencies": [
                    {"name": "flatbuffers", "req": "=25.12.19", "target": "cfg(not(windows))"},
                    {"name": "flatbuffers", "req": "=25.9.23", "target": "cfg(windows)"}
                ]
            }]
        }"#;
        let error =
            require_flatbuffers_runtime_pin(mismatched, "laneflow-road-editing-wire").unwrap_err();
        assert!(error.contains("cfg(windows)"));
        assert!(error.contains("=25.9.23"));
    }

    #[test]
    fn detects_only_standalone_unsafe_token() {
        assert!(contains_unsafe_token("unsafe fn generated() {}"));
        assert_eq!(
            count_unsafe_tokens("unsafe { first() } unsafe { second() }"),
            2
        );
        assert!(!contains_unsafe_token("unsafe_code = \"forbid\""));
        assert!(!contains_unsafe_token("safe_without_unsafe_token"));
    }

    #[test]
    fn strip_non_code_removes_comments_and_literals() {
        // 注释与字面量内容消失，代码 token 原样保留。
        let stripped = strip_non_code(
            "fn f() { unsafe { g() } } // unsafe in comment\n\
             /* block unsafe */ /* nested /* deep unsafe */ still */ let s = \"unsafe in string\";\n\
             let b = b\"unsafe bytes\"; let c = c\"unsafe cstr\";\n\
             let r = r\"unsafe raw\"; let r2 = r##\"unsafe \"quoted\" raw\"##;\n\
             /// doc comment unsafe\n\
             fn documented() {}\n\
             ",
        );
        assert_eq!(count_unsafe_tokens(&stripped), 1, "{stripped}");
        assert!(stripped.contains("fn f()"), "{stripped}");
        assert!(stripped.contains("let s ="), "{stripped}");
        assert!(stripped.contains("fn documented()"), "{stripped}");
        // 生命周期不是字符字面量，后面的代码必须保留。
        let stripped = strip_non_code("fn f<'a>(x: &'a str) -> &'a str { x }");
        assert!(stripped.contains("'a"), "{stripped}");
        assert!(stripped.contains("-> &'a str"), "{stripped}");
        // 字符字面量整体 strip，包括转义形态。
        assert!(!strip_non_code("let c = 'u';").contains('u'));
        assert_eq!(strip_non_code("let q = '\\'';").trim(), "let q =  ;");
        assert_eq!(
            count_unsafe_tokens(&strip_non_code("let e = '\\u{1f600}';")),
            0
        );
        // 块注释未闭合 / 字符串未闭合：strip 到文件尾，不 panic。
        assert_eq!(strip_non_code("ok(); /* dangling unsafe"), "ok();  ");
        assert_eq!(strip_non_code("let s = \"dangling unsafe"), "let s =  ");
        // unsafe 被注释拆半不产生 token，也不与 strip 残留粘连成 token。
        assert_eq!(count_unsafe_tokens(&strip_non_code("uns/* */afe")), 0);
        assert_eq!(count_unsafe_tokens(&strip_non_code("unsafe/*x*/{}")), 1);
    }

    #[test]
    fn strip_non_code_keeps_cfg_gated_unsafe_visible() {
        // cfg 门控不改变文本：feature/profile/平台分支里的 unsafe 都被看见。
        for source in [
            "#[cfg(all(feature = \"a\", not(feature = \"b\")))]\nunsafe fn hidden() {}",
            "#[cfg(not(debug_assertions))]\nunsafe { faster_path() };",
            "#[cfg(windows)]\nmod win { unsafe fn platform() {} }",
        ] {
            assert_eq!(count_unsafe_tokens(&strip_non_code(source)), 1, "{source}");
        }
    }

    #[test]
    fn scans_build_scripts_outside_the_wire_src_directory() {
        let package_root = std::env::temp_dir().join(format!(
            "laneflow-schema-codegen-unsafe-boundary-{}",
            std::process::id()
        ));
        let source_root = package_root.join("src");
        fs::create_dir_all(&source_root).expect("temporary wire source directory");
        let generated_path = source_root.join("runtime-snapshot_generated.rs");
        fs::write(source_root.join("lib.rs"), "pub fn safe_wrapper() {}\n").expect("safe wrapper");
        fs::write(
            package_root.join("build.rs"),
            "unsafe fn hidden_target() {}\n",
        )
        .expect("unsafe build script");

        assert!(check_wire_rust_sources(&package_root, &generated_path).is_err());
        fs::remove_dir_all(&package_root).expect("remove temporary wire package");
    }

    #[test]
    fn detects_source_loading_directives_with_token_whitespace() {
        assert!(contains_source_loading_directive(
            "#[path = \"payload.txt\"]\nmod payload;"
        ));
        assert!(contains_source_loading_directive(
            "#[ path = \"x.txt\"] mod x;"
        ));
        assert!(contains_source_loading_directive(
            "include!(\"payload.rsx\")"
        ));
        assert!(contains_source_loading_directive(
            "include /* 注释 */ ! (\"payload.rsx\")"
        ));
        assert!(contains_source_loading_directive(
            "include ! (\"payload.rsx\")"
        ));
        // include_str! / include_bytes! 只加载数据，不是源码加载指令。
        assert!(!contains_source_loading_directive(
            "const TEXT: &str = include_str!(\"data.txt\");"
        ));
        assert!(!contains_source_loading_directive(
            "const BYTES: &[u8] = include_bytes!(\"data.bin\");"
        ));
        assert!(!contains_source_loading_directive("pub fn plain() {}\n"));
    }

    #[test]
    fn path_attribute_values_accept_package_relative_rs() {
        // forbid 成员的合法用法：tests 指向包内 support 文件。
        check_path_attribute_values(
            "#[path = \"support/snapshot_evidence.rs\"]\nmod snapshot_evidence;",
            "demo",
            PathAttributePolicy::PackageRelativeRs,
        )
        .unwrap();
        // cfg_attr 包裹形态同样被解析，合法值放行。
        check_path_attribute_values(
            "#[cfg_attr(test, path = \"support/cond.rs\")]\nmod cond;",
            "demo",
            PathAttributePolicy::PackageRelativeRs,
        )
        .unwrap();
        // `path` 后未紧跟 `= <字面量>` 不是真实属性（rustc 只接受立即值），跳过。
        check_path_attribute_values(
            "#[path]\nmod never_valid;",
            "demo",
            PathAttributePolicy::PackageRelativeRs,
        )
        .unwrap();
        // trivia 变体同样是真实属性，合法值放行；无 path 的内层属性不受影响。
        check_path_attribute_values(
            "# [path = \"support/cond.rs\"]\nmod cond;",
            "demo",
            PathAttributePolicy::PackageRelativeRs,
        )
        .unwrap();
        check_path_attribute_values(
            "#![allow(unsafe_code)]\nfn f() {}\n",
            "demo",
            PathAttributePolicy::RejectAll,
        )
        .unwrap();
    }

    #[test]
    fn path_attribute_values_reject_escape_and_non_rs() {
        for source in [
            "#[path = \"../../../payload.txt\"]\nmod payload;",
            "#[path = \"../sibling.rs\"]\nmod sibling;",
            "#[path = \"/abs/x.rs\"]\nmod abs;",
            "#[cfg_attr(unix, path = \"nested.txt\")]\nmod nested;",
            "#[path = \"..\\up.rs\"]\nmod up;",
            // `#` 与 `[`（内层属性还有 `!`）之间的 trivia 变体同样是真实属性。
            "# [path = \"../sibling.rs\"]\nmod sibling;",
            "#! [path = \"../sibling.rs\"]",
        ] {
            assert!(
                check_path_attribute_values(source, "demo", PathAttributePolicy::PackageRelativeRs)
                    .is_err(),
                "{source}"
            );
        }
    }

    #[test]
    fn path_attribute_values_skip_comments_and_string_fixtures() {
        // 注释与字面量内容不参与编译：文档与测试固件里的 `#[path]` 字样
        // 不触发误判，即使最严格的 RejectAll 策略也放行。字符字面量里的
        // 方括号不干扰属性区域的配对扫描。
        let source = r##"
            // #[path = "evil.txt"]
            /* #[path = "../evil.rs"] */
            /// doc 提及 `#[path = "evil.txt"]` 形态
            const FIXTURE: &str = "#[path = \"evil.txt\"]\nmod evil;";
            fn brackets() -> char { '[' }
        "##;
        check_path_attribute_values(source, "demo", PathAttributePolicy::RejectAll).unwrap();
    }

    #[test]
    fn path_attribute_values_reject_all_for_mmap_policy() {
        // mmap 例外 crate 的源码全集必须就是包内 .rs 扫描面：
        // 连合法的包内相对 .rs 挂接也一并拒绝。
        let error = check_path_attribute_values(
            "#[path = \"support/ok.rs\"]\nmod ok;",
            "mmap 例外 crate",
            PathAttributePolicy::RejectAll,
        )
        .unwrap_err();
        assert!(error.contains("support/ok.rs"), "{error}");
        // 属性区域未闭合 / 分隔符不配对：无法静态审计，fail closed。
        assert!(
            check_path_attribute_values(
                "#[cfg(test",
                "demo",
                PathAttributePolicy::PackageRelativeRs
            )
            .is_err()
        );
        assert!(
            check_path_attribute_values(
                "#[cfg(test})]",
                "demo",
                PathAttributePolicy::PackageRelativeRs
            )
            .is_err()
        );
    }

    #[test]
    fn cfg_attr_token_detection_respects_ident_boundaries() {
        assert!(contains_cfg_attr_token(
            "#[cfg_attr(test, path = \"x.rs\")]"
        ));
        assert!(contains_cfg_attr_token("cfg_attr"));
        assert!(!contains_cfg_attr_token("let my_cfg_attr = 1;"));
        assert!(!contains_cfg_attr_token("cfg_attrlike();"));
    }

    #[test]
    fn macro_rules_token_detection_respects_ident_boundaries() {
        assert!(contains_bare_token(
            "macro_rules! load { ($m:ident) => { $m!(\"payload.txt\"); } }",
            "macro_rules"
        ));
        assert!(!contains_bare_token("my_macro_rules! {}", "macro_rules"));
        // 宏调用不是定义，不受禁令影响。
        assert!(!contains_bare_token("println!(\"hi\");", "macro_rules"));
    }

    #[test]
    fn metavariable_invocation_detection_respects_macro_grammar() {
        // `$m!`（含 trivia 变体）是元变量调用：可把宏调用名间接化。
        assert!(contains_metavariable_invocation(
            "macro_rules! load { ($m:ident) => { $m!(\"p.txt\"); } }"
        ));
        assert!(contains_metavariable_invocation(
            "macro_rules! load { ($m:ident) => { $m /* mid */ ! (); } }"
        ));
        // $crate 路径、元变量类型标注、重复结构都不是元变量调用。
        assert!(!contains_metavariable_invocation(
            "macro_rules! reexport { () => { $crate::helper!() } }"
        ));
        assert!(!contains_metavariable_invocation(
            "macro_rules! list { ($($x:expr),*) => { vec![$($x),*] } }"
        ));
        assert!(!contains_metavariable_invocation("fn f() { foo!(); }"));
    }

    #[test]
    fn include_identifier_detection_covers_fragmented_forms() {
        // 直接调用。
        assert!(contains_include_identifier("include!(\"payload.rs\");"));
        // 宏体内的标点元变量拼装形态：`include $b ($p)`。
        assert!(contains_include_identifier(
            "macro_rules! load { ($b:tt, $p:literal) => { include $b ($p) } }"
        ));
        // 调用点传参形态：`$m $b ($p)` 的 `include` 在调用点字面出现。
        assert!(contains_include_identifier(
            "macro_rules! load { ($m:ident, $b:tt, $p:literal) => { $m $b ($p) } }\nload!(include, !, \"p.txt\");"
        ));
        // 数据加载宏是不同标识符，不受影响。
        assert!(!contains_include_identifier(
            "const D: &[u8] = include_bytes!(\"d.bin\");"
        ));
        assert!(!contains_include_identifier(
            "const S: &str = include_str!(\"s.txt\");"
        ));
        // 标识符边界：后缀/前缀粘连不匹配。
        assert!(!contains_include_identifier("let my_include = 1;"));
        assert!(!contains_include_identifier("fn include_data() {}"));
    }
}
